### ISSUE TITLE
Netmail handling for other networks than primary one

### ISSUE THREAD

**Issue by joakimmelin** [larsks/crashmail#6]
Crashmail does not seem to be able to handle or route netmail to secondary networks beside Fidonet. 

You can only define one netmail area in crashmail.prefs: 

NETMAIL "NETMAIL" 2:201/120.0 MSG /fido/netmail LATIN-1 DEFAULT

**Comment by larsks** [comment]
Thanks for the bug report! Unfortunately, I'm no longer working with any fidonet related software, so I'm not really in a position to fix crashmail bugs any longer.  I'm leaving the code here in case someone else is interesting in continuing where I left off.

**Comment by joacimmelin** [comment]
Never mind the above.  My mistake.
